/**
 * Address interface - Represents a billing or shipping address
 * Maps to Spring Boot Address entity
 */
export interface Address {
  id?: number;
  street: string;
  city: string;
  state: string;
  zipCode: string;
  country: string;
}

/**
 * Customer interface - Represents a customer entity
 * Maps to Spring Boot Customer entity
 */
export interface Customer {
  id?: number;
  name: string;
  email: string;
  phone: string;
  address: Address;
}

/**
 * InvoiceItem interface - Represents a single line item in an invoice
 * Maps to Spring Boot InvoiceItem entity
 * 
 * @property id - Unique identifier (generated by backend)
 * @property name - Description of the item/service
 * @property quantity - Number of units
 * @property unitPrice - Price per unit
 * @property totalPrice - Calculated as quantity × unitPrice
 * @property invoice - Reference to parent Invoice (optional)
 */
export interface InvoiceItem {
  id?: number;
  name: string;
  quantity: number;
  unitPrice: number;
  totalPrice?: number;
  invoice?: Invoice;
}

/**
 * Invoice interface - Represents a complete invoice document
 * Maps to Spring Boot Invoice entity
 * 
 * @property id - Unique identifier (generated by backend)
 * @property invoiceNumber - Human-readable invoice number (e.g., "INV-2024-001")
 * @property totalAmount - Sum of all invoice items (calculated by backend)
 * @property customer - Customer associated with this invoice
 * @property billingAddress - Address for billing
 * @property invoiceItems - Array of line items in this invoice
 * @property createdDate - When the invoice was created (optional, from backend)
 * @property dueDate - When payment is due (optional, from backend)
 * @property status - Invoice status like "DRAFT", "SENT", "PAID" (optional, from backend)
 */
export interface Invoice {
  id?: number;
  invoiceNumber: string;
  totalAmount: number;
  customer: Customer;
  billingAddress: Address;
  invoiceItems?: InvoiceItem[];
  createdDate?: string;
  dueDate?: string;
  status?: 'DRAFT' | 'SENT' | 'PAID' | 'OVERDUE' | 'CANCELLED';
}

// API Response Type for paginated data
export interface PaginatedResponse<T> {
  content: T[];
  pageable: {
    pageNumber: number;
    pageSize: number;
    sort: {
      empty: boolean;
      sorted: boolean;
      unsorted: boolean;
    };
    offset: number;
    paged: boolean;
    unpaged: boolean;
  };
  last: boolean;
  totalPages: number;
  totalElements: number;
  size: number;
  number: number;
  sort: {
    empty: boolean;
    sorted: boolean;
    unsorted: boolean;
  };
  first: boolean;
  numberOfElements: number;
  empty: boolean;
}

// Error Response Type
export interface ApiError {
  message: string;
  statusCode?: number;
}
